name: expenses_tracker
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Adding dependencies for various features and functionality
  cupertino_icons: ^1.0.8           # For iOS-style icons
  font_awesome_flutter: ^10.8.0     # Font Awesome icons
  fl_chart: ^0.70.1                 # Charting library for visualizations
  intl: ^0.20.1                     # Internationalization and date formatting
  flutter_colorpicker: ^1.1.0       # Color picker for customizable UI

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0             # Recommended lint rules for Flutter projects

flutter:
  uses-material-design: true

  assets:
    - assets/                       # Placeholder for your assets directory
    # Uncomment below lines and add your files as needed
    # - assets/images/
    # - assets/icons/
